### ISSUE TITLE
variables de réception non resetées

### ISSUE THREAD

**Issue by larchuto** [robotronik/common_code#1]
Lorsque l'on donne des valeurs à effectuer à l'asser (ex : "alpha=3142") on peut les écraser tant que la commande liée n'est pas lancée (dans le cas de l'exemple "alpha_delta()") après il semblerait que ça ne soit pas possible.

**Comment by robinmoussu** [comment]
Pas compris, qu'est ce qui n'est pas possible ?

**Comment by larchuto** [comment]
Ceci par exemple :
delta = 500
alpha_delta() //pas de soucis
delta =0 // nécésaire ? (avec ou sans ça ne change rien)
alpha=3142
alpha_delta() // le robot fait un delta de 500 (+ l'alpha de 3142 mais pas sûr, à vérifier)

**Comment by robinmoussu** [comment]
delta = 500
alpha_delta() # deplacement de 500, angle inconnu (dépend de la dernière valeure de alpha envoyé).
delta = 0
alpha=3142
alpha_delta() # deplacement de 0, angle de 3142

À l'initialisation, toutes les variables vallent 0.

Et j'ai toujours pas compris où était le problème.

**Comment by larchuto** [comment]
Le problème est au deuxième appel le robot ne fait pas l'angle demandé mais le delta qui a été déjà éffectué une première fois.

**Comment by robinmoussu** [comment]
Chez moi ça marche, ou alors je n'ai pas compris le problème.

```
# À l'initialisation, toutes les variables valles 0, dont alpha = 0
delta = 500
alpha_delta() # Le robot se déplace bien en ligne droite, vers le haut de 500mm
delta = 0
alpha=3142
alpha_delta() # Le robot fait demi-tour.
```

**Comment by larchuto** [comment]
Je viens de tester sur PC ça à l'air d'être ok en effet. C'est tout à l'heure sur le robot que ça merdait, mais du coup c'est bizarre… Je retesterai ça demain.

**Comment by larchuto** [comment]
Bon aujourd'hui c'était ok… J'ai du me tromper quelque part la dernière fois.
