### ISSUE TITLE
Erreur dans la fonction d'envoi

### ISSUE THREAD

**Issue by Salamandar** [robotronik/common_code#3]
En fait, 
- Sans rien modifier : on se fait spammer de caractères invalides. Comme si l'appel à vprintf ne se terminait pas, et envoyait des machins bizarres
- Si on remplace
  
  ```
   vprintf(format, args);
  ```
  
  par
  
  ```
     //vprintf(format, args);
    printf(format); // Comme une chaîne de caractères simple
  ```
  
  on ne se fait plus spammer et on reçoit bien des trucs du genre "%s%d" quand il faut.

Il y a donc vraiment un soucis avec le format et les arguments, mais je ne saurais absolument pas dire quoi.

NB : pas de soucis sur PC à ce que je sache.

**Comment by robinmoussu** [comment]
Je suppose que tu es sur microcontroleur -> lequel.
Est ce que printf fonctionne ?

**Comment by Salamandar** [comment]
Sur PIC bien sûr pour le moment.
Eh bien printf("une chaine") sans soucis (normalement), mais printf(format, vargs) non.

**Comment by robinmoussu** [comment]
close as duplicate with #4
